version: "3.7"

services:
  database:
    container_name: django-e-learning
    image: postgres
    restart: unless-stopped
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=dead
      - POSTGRES_USER=dead
    ports:
      - "5432:5432"

  memcached:
    container_name: memcached
    image: memcached
    restart: unless-stopped
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64
