version: "3.3"

services:
  database:
    container_name: django-e-learning
    image: postgres
    restart: unless-stopped
    volumes:
    - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=dead
      - POSTGRES_USER=dead
    ports:
      - 5432:5432
